/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface KeyBoard {}
  interface KeyBoardAttributes extends StencilHTMLAttributes {
    'onKeyClicked'?: (event: CustomEvent) => void;
  }

  interface KeyBoard2 {}
  interface KeyBoard2Attributes extends StencilHTMLAttributes {
    'onKeyClicked'?: (event: CustomEvent) => void;
  }

  interface SudokuBoard {
    'board': number[];
    'cellSelected': number;
    'incorrectCells': number[];
  }
  interface SudokuBoardAttributes extends StencilHTMLAttributes {
    'board'?: number[];
    'cellSelected'?: number;
    'incorrectCells'?: number[];
    'onCellSelection'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'KeyBoard': Components.KeyBoard;
    'KeyBoard2': Components.KeyBoard2;
    'SudokuBoard': Components.SudokuBoard;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'key-board': Components.KeyBoardAttributes;
    'key-board2': Components.KeyBoard2Attributes;
    'sudoku-board': Components.SudokuBoardAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLKeyBoardElement extends Components.KeyBoard, HTMLStencilElement {}
  var HTMLKeyBoardElement: {
    prototype: HTMLKeyBoardElement;
    new (): HTMLKeyBoardElement;
  };

  interface HTMLKeyBoard2Element extends Components.KeyBoard2, HTMLStencilElement {}
  var HTMLKeyBoard2Element: {
    prototype: HTMLKeyBoard2Element;
    new (): HTMLKeyBoard2Element;
  };

  interface HTMLSudokuBoardElement extends Components.SudokuBoard, HTMLStencilElement {}
  var HTMLSudokuBoardElement: {
    prototype: HTMLSudokuBoardElement;
    new (): HTMLSudokuBoardElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'key-board': HTMLKeyBoardElement
    'key-board2': HTMLKeyBoard2Element
    'sudoku-board': HTMLSudokuBoardElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'key-board': HTMLKeyBoardElement;
    'key-board2': HTMLKeyBoard2Element;
    'sudoku-board': HTMLSudokuBoardElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
