/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AccButton {}
  interface AccButtonAttributes extends StencilHTMLAttributes {
    'onClick_'?: (event: CustomEvent) => void;
  }

  interface AccSwitch {}
  interface AccSwitchAttributes extends StencilHTMLAttributes {
    'onSwitch'?: (event: CustomEvent) => void;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface KeyBoard {}
  interface KeyBoardAttributes extends StencilHTMLAttributes {
    'onKeyClicked'?: (event: CustomEvent) => void;
  }

  interface KeyBoard2 {}
  interface KeyBoard2Attributes extends StencilHTMLAttributes {
    'onKeyClicked'?: (event: CustomEvent) => void;
  }

  interface SudokuBoardCell {
    'candidates': boolean[];
    'value': number;
  }
  interface SudokuBoardCellAttributes extends StencilHTMLAttributes {
    'candidates'?: boolean[];
    'value'?: number;
  }

  interface SudokuBoard {
    'board': number[];
    'candidatesBoard': boolean[][];
    'cellSelected': number;
    'incorrectCells': number[];
  }
  interface SudokuBoardAttributes extends StencilHTMLAttributes {
    'board'?: number[];
    'candidatesBoard'?: boolean[][];
    'cellSelected'?: number;
    'incorrectCells'?: number[];
    'onCellSelection'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AccButton': Components.AccButton;
    'AccSwitch': Components.AccSwitch;
    'AppRoot': Components.AppRoot;
    'KeyBoard': Components.KeyBoard;
    'KeyBoard2': Components.KeyBoard2;
    'SudokuBoardCell': Components.SudokuBoardCell;
    'SudokuBoard': Components.SudokuBoard;
  }

  interface StencilIntrinsicElements {
    'acc-button': Components.AccButtonAttributes;
    'acc-switch': Components.AccSwitchAttributes;
    'app-root': Components.AppRootAttributes;
    'key-board': Components.KeyBoardAttributes;
    'key-board2': Components.KeyBoard2Attributes;
    'sudoku-board-cell': Components.SudokuBoardCellAttributes;
    'sudoku-board': Components.SudokuBoardAttributes;
  }


  interface HTMLAccButtonElement extends Components.AccButton, HTMLStencilElement {}
  var HTMLAccButtonElement: {
    prototype: HTMLAccButtonElement;
    new (): HTMLAccButtonElement;
  };

  interface HTMLAccSwitchElement extends Components.AccSwitch, HTMLStencilElement {}
  var HTMLAccSwitchElement: {
    prototype: HTMLAccSwitchElement;
    new (): HTMLAccSwitchElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLKeyBoardElement extends Components.KeyBoard, HTMLStencilElement {}
  var HTMLKeyBoardElement: {
    prototype: HTMLKeyBoardElement;
    new (): HTMLKeyBoardElement;
  };

  interface HTMLKeyBoard2Element extends Components.KeyBoard2, HTMLStencilElement {}
  var HTMLKeyBoard2Element: {
    prototype: HTMLKeyBoard2Element;
    new (): HTMLKeyBoard2Element;
  };

  interface HTMLSudokuBoardCellElement extends Components.SudokuBoardCell, HTMLStencilElement {}
  var HTMLSudokuBoardCellElement: {
    prototype: HTMLSudokuBoardCellElement;
    new (): HTMLSudokuBoardCellElement;
  };

  interface HTMLSudokuBoardElement extends Components.SudokuBoard, HTMLStencilElement {}
  var HTMLSudokuBoardElement: {
    prototype: HTMLSudokuBoardElement;
    new (): HTMLSudokuBoardElement;
  };

  interface HTMLElementTagNameMap {
    'acc-button': HTMLAccButtonElement
    'acc-switch': HTMLAccSwitchElement
    'app-root': HTMLAppRootElement
    'key-board': HTMLKeyBoardElement
    'key-board2': HTMLKeyBoard2Element
    'sudoku-board-cell': HTMLSudokuBoardCellElement
    'sudoku-board': HTMLSudokuBoardElement
  }

  interface ElementTagNameMap {
    'acc-button': HTMLAccButtonElement;
    'acc-switch': HTMLAccSwitchElement;
    'app-root': HTMLAppRootElement;
    'key-board': HTMLKeyBoardElement;
    'key-board2': HTMLKeyBoard2Element;
    'sudoku-board-cell': HTMLSudokuBoardCellElement;
    'sudoku-board': HTMLSudokuBoardElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
